name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'never-icons/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'never-icons/**'
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test